### ISSUE TITLE
Script creation fails with paths containing spaces

### ISSUE THREAD

**Issue by SteveBarnegren** [JohnSundell/Marathon#39] opened 2017-04-10 09:39 UTC
Running the creation command from the readme:

`marathon create helloWorld "import Foundation; print(\"Hello world\")"`

Is failing if the run from a folder whose name contains spaces:

`Stevens-MacBook-Pro-2:some scripts stevenbarnegren$ marathon create helloWorld "import Foundation; print(\"Hello world\")"
🐣  Created script at helloWorld.swift
ShellOutError(message: "/bin/bash: line 0: cd: /Users/stevenbarnegren/.marathon/Scripts/Cache/-Users-stevenbarnegren-Desktop-some: No such file or directory", output: "")
`
The swift file is created, but the script is not able to be run via Marathon. Looking at the error, it looks like it is trying to access the directory, but truncating the name at the space.

From a folder on my desktop, named:

`some scripts` fails
`test scripts` fails
`scripts` succeeds

**Comment by JohnSundell** [comment] 2017-04-10 11:18
Thanks for the report @SteveBarnegren! I just made a fix for this bug here: https://github.com/JohnSundell/Marathon/commit/c8c3e4d3c99782af2b8715057490db755ea6cc2b.

Just pull the latest `master` and reinstall Marathon from it, and you should be good to go 😄

**Comment by SteveBarnegren** [comment] 2017-04-10 14:48
@JohnSundell Thanks for the quick fix!

I'm still having some issue running the script though? Creation now works, but running the script still fails?

Creating a script called `hellosteve` in a folder on my desktop called `testing spaces`:

`Stevens-MacBook-Pro-2:testing spaces stevenbarnegren$ marathon create hellosteve "import Foundation; print(\"Hello steve\")"
🐣  Created script at hellosteve.swift
✏️  Opening Hellosteve.xcodeproj/

ℹ️  Marathon will keep running, in order to commit any changes you make in Xcode back to the original script file
   Press any key once you're done

Stevens-MacBook-Pro-2:testing spaces stevenbarnegren$ marathon run hellosteve
💥  Failed to run script
👉  /bin/bash: line 0: cd: /Users/stevenbarnegren/Desktop/testing: No such file or directory
`

**Comment by pixyzehn** [comment] 2017-04-10 15:20
@SteveBarnegren 
I think the problem is `testing spaces` has a white space, so you can run a script by using `testing_spaces` or `testingSpaces` folder.
I'll fix the bug if possible.

**Comment by JohnSundell** [comment] 2017-04-10 15:38
@pixyzehn @SteveBarnegren I must've missed to update all the code paths that `run` can take. Will fix now 👍 Curious that my test case for this passes, so will need to take a look at that as well 😅

**Comment by JohnSundell** [comment] 2017-04-10 15:39
Ah, I know why. It's because the **current folder** has spaces. Will make a fix for that now.

**Comment by JohnSundell** [comment] 2017-04-10 16:00
Alright, just pushed a commit that should fully fix this. I was able to reproduce the problem in a test case, which is now passing 👍 

@SteveBarnegren could you run from the latest `master` and verify the fix? 🙂

**Comment by SteveBarnegren** [comment] 2017-04-10 16:15
Works like a charm! Thanks @JohnSundell 👍

**Comment by JohnSundell** [comment] 2017-04-10 16:51
@SteveBarnegren Fantastic 🎉 Closing this now then.

**Closed by JohnSundell** 2017-04-10 16:51 UTC
Labels: bug, fixed
