### ISSUE TITLE
Cannot add packages which has a version tag containing non-numeric characters

### ISSUE THREAD

**Issue by kareman** [JohnSundell/Marathon#17] opened 2017-03-28 18:42 UTC
```
~/Downloads> marathon add git@github.com:kareman/SwiftShell.git 
💥  Could not resolve the latest version for package at 'git@github.com:kareman/SwiftShell.git'
👉  Make sure that the package you're trying to add is reachable, and has at least one tagged release
```

I think this may be the reason:

```
~/Downloads/Marathon> git ls-remote --tags https://github.com/kareman/SwiftShell 
c28ab4b7561a0ae9fe1f653da39ae98ed7cec67e	refs/tags/2.0.0
d77285c1520f12d03d28b70ae744cb2b1664d838	refs/tags/2.0.0^{}
7310d2af9312ccab679e3debada2472dbcb127c8	refs/tags/2.0.1
97c49c031ae4d26986d6fa03ccd625d4b026cee0	refs/tags/2.0.1^{}
dc3f92f450d5c3b68a974b93268e8fe474e473bd	refs/tags/2.0.2
02b93bc4eccf3552f9f860ee2d2ef597dd778810	refs/tags/2.0.2^{}
37319375302935189ffb89410ba826fa8a86fce9	refs/tags/2.1
7b73ae7be0979907fc339a69bb3a21c5af39ffa7	refs/tags/2.1^{}
417eca4f311fef8a97e33e31c9be38c7a31fc5f0	refs/tags/3.0.0-beta.1
ed371b7e639071a026c0a7e0adb7a2a813f5ff40	refs/tags/3.0.0-beta.1^{}
fa70e419dd6c2fce71bfc6e07bb352186240b3b6	refs/tags/3.0.0-beta.10
d9444645784bcd751526e672bb6e8c933ac2c27c	refs/tags/3.0.0-beta.11
e69c3859c0940af2a01f6ecdb2d4b18853b424da	refs/tags/3.0.0-beta.12
21a385f198bc2af6b0fede532abb045407b0f95a	refs/tags/3.0.0-beta.12^{}
f900b101bc2290490cc1d6f6efcecd381bceecad	refs/tags/3.0.0-beta.2
2e27a6d776f22568247360da5c38ce37707bfcf2	refs/tags/3.0.0-beta.2^{}
a67516033e224ce809332e7e2f788ef8b354a7f2	refs/tags/3.0.0-beta.3
22dd184b698f74b43565f8cdd7ca0fd1005cfb3b	refs/tags/3.0.0-beta.3^{}
cdefffe73984ce2747a4b549b0fafa16f629b66b	refs/tags/3.0.0-beta.4
1a24474a32ae8b6cf66a42ce8910abb37da08256	refs/tags/3.0.0-beta.4^{}
97a769521fa04d1f745c2dd48db74a84814a5b0b	refs/tags/3.0.0-beta.5
eea3cd2d61a318f82984598029f2b3339c7a7375	refs/tags/3.0.0-beta.5^{}
7aae88446a0ce92a9e68cc82f8fd4dfed5109619	refs/tags/3.0.0-beta.6
25f64feceb5ebf39607e2ffa89f4aa64e1335ca7	refs/tags/3.0.0-beta.6^{}
31786bb0c2c48be727739d4259ec70c18fef56ca	refs/tags/3.0.0-beta.7
5dd2da16f097cb014423d8e486bb10e86830011c	refs/tags/3.0.0-beta.7^{}
4145afefd85a51beb57490e7d3d94111d8aa800c	refs/tags/3.0.0-beta.8
62780a880aaad2c3e12aa1619c48538b24703c7d	refs/tags/3.0.0-beta.9
d1e9688039ee208fea546a3ccf143346db1b657a	refs/tags/v0.1
9555306183e7a5c84bc342a76c5b5f9a189a2f17	refs/tags/v0.1^{}
70286ffa67f644f483c5ca50671f94473a6c10e5	refs/tags/v0.2
5564eec6c71fbfc7109e3af802f73158626c5dd8	refs/tags/v0.2^{}
27066b8d2785b823872750dcd07cc06532f9f8b6	refs/tags/v1.0
301bc4b29db848b143b18d92f1e77ec7116f1f7f	refs/tags/v1.0^{}
a8bf55096283f959b6397a3055e5b8f50d9550c2	refs/tags/v1.1
a7a68866a19eb41e85083a23025a95e19bbd1dc6	refs/tags/v1.1^{}
616eced7bb9e42805038ce67136c7c4c85f20b18	refs/tags/v2.0b1
12fb5b2a5c85fdc3e3ce86b8d9cb8a92a3b0210a	refs/tags/v2.0b1^{}
7560b936769387346a8570e42c5a2a7989de1858	refs/tags/v2.0b2
5ac1b5f6909531444d5798a5f6a3fb937e6577fa	refs/tags/v2.0b2^{}
```

Either because the latest version is a beta version (3.0.0-beta.12), or because the first version tags start with 'v' but not the later ones, and Git sorts them alphabetically instead of chronologically for some reason. I had to stop using 'v' to support Swift package manager if I remember correctly.

**Comment by JohnSundell** [comment] 2017-03-28 21:50
Thanks for the report @kareman! 👍 It's indeed caused by the tags containing `v`. Marathon tries to parse the latest major version (see `PackageManager.majorVersion(from:)`) and fails because it `Int(string)` fails for the string `v2` 💥

I'm thinking the expected behavior here is to add version `2.1`, right? Because the other releases are betas, so you wouldn't want them added (maybe we can allow it through an `--beta` argument or something).

It seems like the assumption that the last tag is always the latest version does not stand in this case, so to make the logic more rigid I think the right thing do to is to iterate over all tags and find the highest version that does not include `alpha`, `beta` (and maybe `pre` and `prerelease`) - and use that version.

What do you think @kareman, would that work?

**Comment by kareman** [comment] 2017-03-28 22:10
Sounds like a good plan. Have you considered importing the Swift Package Manager project itself? In addition to handling swift package projects they have also implemented [Version](https://github.com/apple/swift-package-manager/blob/master/Sources/PackageDescription/Version.swift). And made it Comparable so you can sort it.

**Comment by JohnSundell** [comment] 2017-03-28 22:57
@kareman Yeah, that's definitely something I'm considering for the future. They are working on making it even more usable as a library, so I'm going to start experimenting with that soon for sure 👍 For now, let's do the implementation in Marathon. I can probably find some time to work on this tomorrow evening 🙂, unless you want to do it of course?

**Comment by kareman** [comment] 2017-03-28 23:35
I don't have time this week I'm afraid. I can take a look at it next week if you haven't already done it by then.

**Comment by JohnSundell** [comment] 2017-03-29 17:47
@kareman No worries at all, I'll take care of it tonight 😄

**Comment by JohnSundell** [comment] 2017-03-29 23:07
Had to fix some other things tonight, but I'll have time later this week for sure :)

**Comment by JohnSundell** [comment] 2017-03-31 12:56
@kareman This has now been fixed in https://github.com/JohnSundell/Marathon/commit/54893ce56f261e13f619f39b0537860f46bfc05b 🎉 

However, you won't be able to use SwiftShell just yet, because the latest stable version `2.1` does not have a layout compatible with the Swift Package Manager. I'd recommend either tagging a `2.2` version that has the correct layout, or waiting until `3.0` is ready to go out of beta.

**Comment by kareman** [comment] 2017-03-31 14:23
Excellent. Swiftshell will hopefully be out of beta next week so I'll try again then.

**Comment by JohnSundell** [comment] 2017-03-31 14:34
@kareman Awesome! Mind if I close this issue?

**Comment by kareman** [comment] 2017-03-31 14:47
Not at all.

**Comment by JohnSundell** [comment] 2017-03-31 15:00
@kareman Cool - let me know once you have deployed a new version of Swiftshell if you still encounter any problems adding it to Marathon 🙂

**Closed by JohnSundell** 2017-03-31 15:00 UTC
Labels: bug, fixed
