### ISSUE TITLE
Compile Error: node is produced by multiple commands

### ISSUE THREAD

**Issue by melbic** [JohnSundell/Marathon#99] opened 2017-06-07 06:45 UTC
Hey,
I just tried to create a simple script, but unfortunately I can't get it to compile.
The script in its simplest form (`dokkuFetcher.swift`):
```swift
import Foundation
print("hello world!")
```
`marathon run dokkuFetcher --verbose` has the following output:
```bash
🏃  $ cd "/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/.build/" && ln -s "/Users/me/.marathon/Packages/Generated/.build/checkouts/" "checkouts"

   $ cd "/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/.build/" && ln -s "/Users/me/.marathon/Packages/Generated/.build/repositories/" "repositories"

   $ cd "/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/.build/" && ln -s "/Users/me/.marathon/Packages/Generated/.build/workspace-state.json" "workspace-state.json"

   $ cd "/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/" && ln -s "/Users/me/Scripts/DokkuFetcher/dokkuFetcher.swift" "OriginalFile"

   $ cd "/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/" && readlink OriginalFile
   /Users/me/Scripts/DokkuFetcher/dokkuFetcher.swift
   $ cd "/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/" && /usr/bin/env xcrun --sdk macosx swift build -C /Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/ --enable-prefetching
   Compile Swift Module 'SwiftShell' (9 sources)
   Compile Swift Module 'ShellOut' (1 sources)
   Compile Swift Module 'Require' (1 sources)
   Compile Swift Module 'Releases' (4 sources)
   <unknown>:0: error: unable to build node: '/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/.build/debug/Files.swiftmodule' (node is produced by multiple commands; e.g., '<Xgen.module>' and '<Files.module>')
   <unknown>:0: error: unable to build node: '/Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/.build/debug/Files.build/Files.swift.o' (node is produced by multiple commands; e.g., '<Xgen.module>' and '<Files.module>')
   swift-build: error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/me/.marathon/Scripts/Cache/-Users-me-Scripts-DokkuFetcher-dokkuFetcher/.build/debug.yaml
💥  Failed to compile script
```
Additionally to the default dependencies I added: https://github.com/kareman/SwiftShell
What did I do wrong?

**Comment by cojoj** [comment] 2017-06-07 07:11
@melbic can you tell us which Swift version was used to compile this?

**Comment by melbic** [comment] 2017-06-07 07:13
```bash
swift --version
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9
```

**Comment by cojoj** [comment] 2017-06-07 07:58
@melbic huh, I have no clue... I have the same version and I'll try to play with it to reproduce this issue. Does it happen everytime for you?

**Comment by JohnSundell** [comment] 2017-06-07 08:06
@melbic @cojoj This issue happens when the Swift Package Manager builds the same package multiple times. This should normally not happen (because of dependency graph resolution), but there seems to be a bug that causes SPM to get confused if the same package appears in the graph but with different URLs.

For example, adding Files using the URL `git@github.com:johnsundell/files.git` on the top level, while including another package that depends on Files using the URL `https://github.com/johnsundell/files.git`.

This is something that we should work around in Marathon until it has been fixed in SPM, but it's easier said than done, since we'd have to go in and manipulate dependencies for added packages. But it's something I'm hoping to look into soon 🙂

In the meantime, make sure all your package URLs are normalized (for example, all using HTTPS with the same casing). If you run `marathon list` you'll be able to see all the top level URLs, and then you can check your packages' `Package.swift` file to make sure the URLs match.

The output suggests that Files is the problem. Xgen depends on Files using `https://github.com/JohnSundell/Files.git`, so make sure your `marathon list` output contains the same URL for Files, otherwise `marathon remove Files && marathon add https://github.com/JohnSundell/Files.git`.

Hope this helps 😄

**Comment by melbic** [comment] 2017-06-10 13:02
Perfect, that did fix the problem.
Thanks for the answer.

**Closed** 2017-06-10 15:17 UTC
Labels: answered, question
